# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6bc2f748560cde2b1687bb521215877052f7285a3f9ae7b227cdb15c8016ac2d62689968ef8c2ffca42fdc6f731fa488f55d5930c39fdabd221c4447b79e2b5

test:
  secret_key_base: c9137cc75f3b741e654f0089bed3ccf63b5063ed7157c2cb35684e880655317ba80ee7d261144cabcba1c508dba5e15a7451e924f1d461fbeed706960f813108

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
